apiVersion: vshn.appcat.vshn.io/v1
kind: VSHNPostgreSQL
metadata:
  name: pgsql-app1-prod 
spec:
  parameters:
    service:
      majorVersion: "15" 
  writeConnectionSecretToRef:
    name: postgres-creds 